name: Build Executables

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Create virtual environment
        run: |
          python -m venv venv
          .\venv\Scripts\Activate.ps1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Build with PyInstaller
        run: |
          pyinstaller watermark.spec
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v2
        with:
          name: s42_watermark-windows
          path: dist/s42_watermark.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Build with PyInstaller
        run: pyinstaller watermark.spec
      - name: Compress .app bundle
        run: |
          cd dist
          zip -r s42_watermark.zip s42_watermark.app
      - name: Upload macOS artifact
        uses: actions/upload-artifact@v2
        with:
          name: s42_watermark-macos
          path: dist/s42_watermark.zip